version: '3.8'

services:    
  eureka-sv:
    container_name: "eureka-sv"
    image: eureka:1
    build: eureka-sv
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'tiendaelectrodomesticos-network'

  mysql-db:
    container_name: "mysql-db"
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - 'tiendaelectrodomesticos-network'

  product-service:
    container_name: "product-service"
    image: product:1
    build: product-service
    ports:
      - "8084:8084"
    environment:
      DATABASE_URL: "jdbc:mysql://mysql-db:3306/product_service?createDatabaseIfNotExist=true"
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      - mysql-db
    networks:
      - 'tiendaelectrodomesticos-network'

  cart-service:
    container_name: "cart-service"
    image: cart:1
    build: cart-service
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: "jdbc:mysql://mysql-db:3306/cart_service?createDatabaseIfNotExist=true"
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      - mysql-db
    networks:
      - 'tiendaelectrodomesticos-network'

  sales-service:
    container_name: "sales-service"
    image: sales:1
    build: sales-service
    ports:
      - "8083:8083"
    environment:
      DATABASE_URL: "jdbc:mysql://mysql-db:3306/sales_service?createDatabaseIfNotExist=true"
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      - mysql-db
    networks:
      - 'tiendaelectrodomesticos-network'

  api-gateway:
    container_name: "api-gateway"
    image: api-gateway:1
    build: api-gateway
    ports:
      - "8086:8086"
    depends_on:
      - eureka-sv
    networks:
      - 'tiendaelectrodomesticos-network'

volumes:
  mysql-db-data:

networks:
  tiendaelectrodomesticos-network:
